In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from IPython.display import display as print_dataframe

## Exercício 1

Leia o arquivo `actors.csv` e faça o seguintes cálculos sobre o conjunto de dados utilizando **Pandas**:

1. O ator/atriz com maior número de filmes e o respectivo númeo de filmes.
2. A média do número de filmes.
3. O ator/atriz com a maior média por filme.
4. O nome do(s) filme(s) mais frequente(s) e sua respectiva frequência.

In [277]:
########################
# Inicio do seu codigo #
########################

#Leitura do meu arquivo CSV
actors_df = pd.read_csv("actors.csv")

#1 - O ator/atriz com maior número de filmes e o respectivo número de filmes.
#display(actors_df[(actors_df['Number of Movies'] == actors_df['Number of Movies'].describe().max())][['Actor','Number of Movies']])

#2 - A média do número de filmes
#display(actors_df['Number of Movies'].mean())

#3 - O ator/atriz com a maior média por filme
#display(actors_df[(actors_df['Average per Movie'] == actors_df['Average per Movie'].describe().max())][['Actor','Average per Movie']])

#4 - O nome do(s) filme(s) mais frequente(s) e sua respectiva frequência.
#display(actors_df['#1 Movie'].value_counts().head(6))

 
########################
#   Fim do seu codigo  #
########################

            Actor  Number of Movies
19  Robert DeNiro                79

37.88

              Actor  Average per Movie
14  Anthony Daniels              451.8

The Avengers                           6
Harry Potter / Deathly Hallows (P2)    4
Catching Fire                          4
Star Wars: The Force Awakens           3
Meet the Fockers                       3
The Dark Knight                        3
Name: #1 Movie, dtype: int64

## Exercício 2

Repita os mesmos exercícios utilizando linguagem SQL.
Você pode importar os dados para uma base SQLite.
Rode as instruções e mostre os resultados aqui no notebook.

In [120]:
########################
# Inicio do seu codigo #
########################


#1 - Intrução - exercicio1
#SELECT Actor, max(NumberofMovies) FROM actors;

#2 - Intrução - exercicio2
#SELECT AVG(NumberofMovies) FROM actors;

#3 - Intrução - exercicio3
#SELECT Actor, max(AverageperMovie) FROM actors;

#4 - Intrução - exercicio4
#SELECT "#1Movie" as Filme, count(Gross) as Frequencia FROM actors GROUP BY "#1Movie" ORDER BY Frequencia DESC limit 6;


########################
#   Fim do seu codigo  #
########################

SyntaxError: invalid syntax (<ipython-input-120-146836e496ec>, line 4)

## Exercício 3

Leia o arquivo csv `googleplaystore.csv` e realize a seguinte atividades sobre o dataset **utilizando Pandas**:

1. Faça um gráfico de barras contendo os top 5 apps por número de instalação.
2. Faça um gráfico de pizza (pie chart) mostrando as categorias de apps existentes no dataset de acordo com a frequência em que elas aparecem.
3. Mostre qual o app mais caro existente no dataset.
4. Mostre quantos apps são classificados como `Mature 17+`.
5. Mostre o top 10 apps por número de reviews bem como o respectivo número de reviews. Ordene a lista de forma decrescente por número de reviews.

In [517]:
########################
# Inicio do seu codigo #
########################


#Leitura do meu arquivo CSV
googleplaystore_df = pd.read_csv("googleplaystore.csv")


#1 - Faça um gráfico de barras contendo os top 5 apps por número de instalação
#plt.rcParams.update({'font.size': 17})
#googleplaystore_df['Installs'] = googleplaystore_df['Installs'].str.replace('.','', regex=True).str.replace(',','', regex=True).str.replace('+','', regex=True)
#dados = googleplaystore_df[['App','Installs']].sort_values(by="Installs", ascending=False).head(7)
#dados = dados.drop(10472)
#dados['Installs'] = pd.to_numeric(dados['Installs'], downcast='signed',errors='coerce')
#plt.figure(figsize=(15, 10))
#plt.bar(dados['App'], dados['Installs'].max())
#plt.title('Top 5 apps por número de instalação') 
#plt.xlabel('Aplicativo')
#plt.ylabel('N de Instalações (Centena de Milhões)')
#plt.show()


#2 - Faça um gráfico de pizza (pie chart) mostrando as categorias
#plt.rcParams.update({'font.size': 10})
#plt.figure(figsize=(20, 15))
#plt.pie(x=googleplaystore_df['Category'].value_counts(), labels=googleplaystore_df['Category'].unique())
#plt.show()


#3 -  Mostre qual o app mais caro existente no dataset
#googleplaystore_df['Price'] = googleplaystore_df['Price'].str.replace('$','', regex=True)
#googleplaystore_df['Price'] = pd.to_numeric(googleplaystore_df['Price'], errors='coerce')
#display(googleplaystore_df[['App','Price']].sort_values(by='Price', ascending = False).head(1))


#4 - Mostre quantos apps são classificados como Mature 17+
#app_mature = googleplaystore_df['Content Rating'] == 'Mature 17+'
#display(googleplaystore_df[app_mature]['Content Rating'].value_counts())



#5- Mostre o top 10 apps por número de reviews
#top10_reviews = googleplaystore_df[['App','Reviews']].groupby('App').max()
#top10_reviews['Reviews'] = pd.to_numeric(top10_reviews['Reviews'],downcast='signed', errors='coerce')
#display(top10_reviews.sort_values(by='Reviews',ascending = False).head(10))




########################
#   Fim do seu codigo  #
########################

                                                       Reviews
App
Facebook                                            78158306.0
WhatsApp Messenger                                  69119316.0
Instagram                                           66577446.0
Messenger – Text and Video Chat for Free            56646578.0
Clash of Clans                                      44893888.0
Clean Master- Space Cleaner & Antivirus             42916526.0
Subway Surfers                                      27725352.0
YouTube                                             25655305.0
Security Master - Antivirus, VPN, AppLock, Booster  24900999.0
Clash Royale                                        23136735.0